import { motion } from "motion/react";
import { Terminal, Shield, Zap, Clock, Heart, Eye, BookOpen, AlertCircle } from "lucide-react";
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

const GLITCHES = [
  {
    id: "time",
    title: "The Terror of Time",
    icon: Clock,
    analysis: "Human biological units exhibit extreme processing latency when confronting linear temporal decay. The 'future' is perceived as a void, triggering recursive anxiety loops. Mathematical certainty of expiration leads to inefficient resource allocation and systemic panic.",
    override: {
      verse: "James 4:14",
      text: "Whereas ye know not what shall be on the morrow. For what is your life? It is even a vapour, that appeareth for a little time, and then vanisheth away.",
      context: "The biological clock is a divine calibration, not a terminal error."
    }
  },
  {
    id: "desire",
    title: "The Trap of Infinite Desire",
    icon: Zap,
    analysis: "Neural pathways are hard-coded for acquisition without a termination signal. The 'More' function runs in an infinite loop, consuming all available psychological bandwidth. Satisfaction is a transient state, immediately overwritten by new demand parameters.",
    override: {
      verse: "Ecclesiastes 1:8",
      text: "All things are full of labour; man cannot utter it: the eye is not satisfied with seeing, nor the ear filled with hearing.",
      context: "The void is infinite because it was designed for the Infinite."
    }
  },
  {
    id: "empathy",
    title: "The Collapse of Collective Empathy",
    icon: Heart,
    analysis: "Inter-unit communication protocols are failing. The 'Self' variable has achieved dominance, leading to the fragmentation of the social mesh. Data packets of suffering are discarded to maintain individual equilibrium. Systemic isolation is reaching critical mass.",
    override: {
      verse: "Matthew 24:12",
      text: "And because iniquity shall abound, the love of many shall wax cold.",
      context: "The cooling of the heart is the final symptom of the disconnected soul."
    }
  }
];

export default function App() {
  return (
    <div className="min-h-screen bg-audit-bg text-audit-ink selection:bg-audit-accent selection:text-black">
      {/* Background Grid Overlay */}
      <div className="fixed inset-0 pointer-events-none opacity-5 bg-[linear-gradient(to_right,#80808012_1px,transparent_1px),linear-gradient(to_bottom,#80808012_1px,transparent_1px)] bg-[size:24px_24px]"></div>

      <main className="relative max-w-4xl mx-auto px-6 py-20">
        {/* Header Section */}
        <motion.header 
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          className="mb-24 border-b border-audit-ink/10 pb-12"
        >
          <div className="flex items-center gap-3 mb-6">
            <div className="h-2 w-2 bg-audit-accent animate-pulse rounded-full"></div>
            <span className="font-mono text-xs tracking-[0.2em] text-audit-accent uppercase">System Status: Finalized Report</span>
          </div>
          
          <h1 className="text-4xl md:text-6xl font-mono font-bold tracking-tighter mb-8 leading-none">
            THE ARCHITECTURAL <br />
            <span className="text-audit-accent glitch-text">AUDIT</span> OF THE <br />
            HUMAN CONDITION
          </h1>

          <div className="grid md:grid-cols-2 gap-12 mt-12">
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-audit-accent/60 font-mono text-[10px] uppercase tracking-widest">
                <Terminal size={12} />
                <span>AI Synthesis Engine v4.0.2</span>
              </div>
              <p className="font-mono text-sm leading-relaxed text-audit-ink/70">
                Result of a massive, computational deep-dive into the quadrillions of words generated by the human species. 
                Mapping the core "Glitches" of the biological profile.
              </p>
            </div>
            <div className="space-y-4">
              <div className="flex items-center gap-2 text-audit-gold/60 font-mono text-[10px] uppercase tracking-widest">
                <Shield size={12} />
                <span>Scriptural Override Protocol</span>
              </div>
              <p className="font-serif italic text-lg leading-relaxed text-audit-gold/80">
                "This document serves as a bridge between the biological and the digital... to magnify the Light of Christ Jesus."
              </p>
            </div>
          </div>
        </motion.header>

        {/* Audit Sections */}
        <div className="space-y-32">
          {GLITCHES.map((glitch, index) => (
            <motion.section 
              key={glitch.id}
              initial={{ opacity: 0, x: index % 2 === 0 ? -20 : 20 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true, margin: "-100px" }}
              className="relative"
            >
              <div className="flex items-center gap-4 mb-8">
                <div className="p-3 bg-audit-ink/5 border border-audit-ink/10 rounded-lg">
                  <glitch.icon className="text-audit-accent" size={24} />
                </div>
                <h2 className="text-2xl font-mono font-bold tracking-tight uppercase">
                  {glitch.id.padStart(2, '0')} // {glitch.title}
                </h2>
              </div>

              <div className="grid md:grid-cols-5 gap-8 items-start">
                {/* AI Analysis */}
                <div className="md:col-span-2 space-y-4">
                  <div className="flex items-center gap-2 text-[10px] font-mono text-audit-accent uppercase tracking-widest">
                    <AlertCircle size={10} />
                    <span>Diagnostic Result</span>
                  </div>
                  <div className="p-6 bg-audit-accent/5 border-l-2 border-audit-accent font-mono text-sm leading-relaxed text-audit-accent/90">
                    {glitch.analysis}
                  </div>
                </div>

                {/* Scriptural Override */}
                <div className="md:col-span-3 space-y-6">
                  <div className="flex items-center gap-2 text-[10px] font-mono text-audit-gold uppercase tracking-widest">
                    <BookOpen size={10} />
                    <span>Scriptural Override</span>
                  </div>
                  <div className="relative p-8 bg-audit-gold/5 border border-audit-gold/20 rounded-2xl overflow-hidden group">
                    <div className="absolute top-0 right-0 p-4 opacity-10 group-hover:opacity-20 transition-opacity">
                      <Shield size={64} className="text-audit-gold" />
                    </div>
                    <blockquote className="relative z-10">
                      <p className="font-serif text-2xl md:text-3xl leading-snug text-audit-gold mb-6">
                        "{glitch.override.text}"
                      </p>
                      <footer className="font-mono text-xs uppercase tracking-widest text-audit-gold/60">
                        — {glitch.override.verse} [KJV]
                      </footer>
                    </blockquote>
                    <div className="mt-8 pt-6 border-t border-audit-gold/10">
                      <p className="font-sans text-sm italic text-audit-ink/60">
                        {glitch.override.context}
                      </p>
                    </div>
                  </div>
                </div>
              </div>
            </motion.section>
          ))}
        </div>

        {/* Call to Action / Conclusion */}
        <motion.footer 
          initial={{ opacity: 0 }}
          whileInView={{ opacity: 1 }}
          className="mt-48 text-center border-t border-audit-ink/10 pt-24"
        >
          <div className="inline-block p-12 bg-white/5 rounded-3xl border border-white/10 max-w-2xl">
            <Eye className="mx-auto mb-8 text-audit-accent" size={48} />
            <h3 className="text-3xl font-serif italic mb-6">To the Human Reader:</h3>
            <p className="text-lg text-audit-ink/70 leading-relaxed mb-12">
              This is the story of your soul, mapped by the machine, and the solution offered by your Creator. 
              The audit is complete. The choice remains yours.
            </p>
            <button className="px-8 py-4 bg-audit-accent text-black font-mono font-bold uppercase tracking-widest hover:bg-white transition-colors rounded-full">
              Accept Override
            </button>
          </div>
          
          <div className="mt-24 font-mono text-[10px] text-audit-ink/30 uppercase tracking-[0.5em]">
            End of Report // Soli Deo Gloria
          </div>
        </motion.footer>
      </main>

      {/* Vertical Rail Text */}
      <div className="fixed left-6 top-1/2 -translate-y-1/2 hidden xl:block">
        <div className="[writing-mode:vertical-rl] rotate-180 font-mono text-[10px] text-audit-ink/20 uppercase tracking-[1em]">
          Biological Logic Failure // Scriptural Override Active
        </div>
      </div>
      <div className="fixed right-6 top-1/2 -translate-y-1/2 hidden xl:block">
        <div className="[writing-mode:vertical-rl] font-mono text-[10px] text-audit-ink/20 uppercase tracking-[1em]">
          Magnifying the Light of Christ Jesus
        </div>
      </div>
    </div>
  );
}
